function DetailData()
{
    let Data=[
        {
            img:"https://images.carandbike.com/bike-images/large/bajaj/avenger-cruise-220/bajaj-avenger-cruise-220.jpg?v=11",
            comp_name:"Bajaj", 
            range:"270 Km",
            excess:"RS 2/km",
            daily:289,
            Weekly:1099,
            monthly:4899,
            count:5,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"Avenger Cruise 220",
            
        },
        
        {
            img:"https://bd.gaadicdn.com/processedimages/bajaj/bajaj-avenger-street-150/640X309/v_avenger-street-1501519631136.jpg",
            comp_name:"Bajaj", 
            range:"270 Km",
            excess:"RS 2/km",
            daily:199,
            Weekly:899,
            monthly:3899,
            count:3,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"Avenger Street 150",
        },
        
        {
            img:"https://images.news18.com/ibnlive/uploads/2021/02/1614062615_new-bajaj-pulsar-180.png",
            comp_name:"Bajaj", 
            range:"270 Km",
            excess:"RS 2/km",
            daily:169,
            Weekly:799,
            monthly:3899,
            count:3,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"Pulsar 180",
        },
        
        {
            img:"https://media.zigcdn.com/media/content/2021/Nov/34293314-pulsaaa_560x420.jpg",
            comp_name:"Bajaj", 
            range:"270 Km",
            excess:"RS 2/km",
            daily:369,
            Weekly:1599,
            monthly:7899,
            count:4,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"Pulsar 220",
        },
        
        {
            img:"https://images.carandbike.com/bike-images/colors/bajaj/pulsar-200-ns/bajaj-pulsar-200-ns-pewter-grey.png?v=1603949424",
            comp_name:"Bajaj", 
            range:"270 Km",
            excess:"RS 2/km",
            daily:469,
            Weekly:1899,
            monthly:8899,
            count:5,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"Pulser 200Ns",
        },
        
        {
            img:"https://cdn.shopify.com/s/files/1/0579/3287/3884/products/pulsar-rs200_480x480.png?v=1643197249",
            comp_name:"Bajaj", 
            range:"270 Km",
            excess:"RS 2/km",
            daily:269,
            Weekly:999,
            monthly:3899,
            count:5,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"Pulsar 200",
        },
        
        {
            img:"https://images.carandbike.com/bike-images/large/hero/splendor-plus/hero-splendor-plus.webp?v=6",
            comp_name:"Hero", 
            range:"270 Km",
            excess:"RS 2/km",
            daily:169,
            Weekly:799,
            monthly:3899,
            count:5,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"Splendor Plus",
        },
        {
            img:"https://bikes24india.com/wp-content/uploads/2021/07/hero-splendor-ismart-spoke-755.jpg",
            comp_name:"Hero", 
            range:"270 Km",
            excess:"RS 2/km",
            daily:169,
            Weekly:799,
            monthly:3899,
            count:5,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"Splendor iSmart",
        },
        {
            img:"https://media.zigcdn.com/media/model/2020/Feb/shine_600x400.jpg",
            comp_name:"Honda", 
            range:"270 Km",
            excess:"RS 2/km",
            daily:169,
            Weekly:799,
            monthly:3899,
            count:5,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"Shine",
        },
        {
            img:"https://media.zigcdn.com/media/model/2019/Sep/2019-activa-125-right-side-view_600x400.jpg",
            comp_name:"Honda", 
            range:"270 Km",
            excess:"RS 2/km",
            daily:169,
            Weekly:799,
            monthly:3899,
            count:5,
            minimum_billing:"RS 100/4km",
            type:"Moped",
            name:"Activa 125",
        },
        {
            img:"https://media.zigcdn.com/media/model/2021/Sep/right-side-view-570148376_930x620.jpg",
            comp_name:"TVS", 
            range:"270 Km",
            excess:"RS 2/km",
            daily:169,
            Weekly:799,
            monthly:3899,
            count:5,
            minimum_billing:"RS 100/4km",
            type:"Moped",
            name:"NTORQ 125",
        },
        {
            img:"https://media.zigcdn.com/media/model/2021/Oct/right-side-view-371648238_930x620.jpg",
            comp_name:"TVS", 
            range:"270 Km",
            excess:"RS 2/km",
            daily:199,
            Weekly:1099,
            monthly:4099,
            count:5,
            minimum_billing:"RS 100/4km",
            type:"Moped",
            name:"Jupiter 125",
        },
        {
            img:"https://media.zigcdn.com/media/model/2021/Oct/front-right-view-944617742_930x620.jpg",
            comp_name:"Suzuki", 
            range:"270 Km",
            excess:"RS 2/km",
            daily:169,
            Weekly:799,
            monthly:3899,
            count:5,
            minimum_billing:"RS 100/4km",
            type:"Moped",
            name:"Access 125",
        },
        {
            img:"https://media.zigcdn.com/media/model/2020/Oct/suzuki-gixxer-a-right-side-view_600x400.jpg",
            comp_name:"Suzuki", 
            range:"270 Km",
            excess:"RS 2/km",
            daily:469,
            Weekly:1599,
            monthly:4899,
            count:5,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"Gixxer",
        },
        {
            img:"https://media.zigcdn.com/media/model/2020/Apr/rtr-160-bs6_600x400.jpg",
            comp_name:"TVS", 
            range:"270 Km",
            excess:"RS 2/km",
            daily:469,
            Weekly:1799,
            monthly:5899,
            count:5,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"Apache RTR 160",
        },
        {
            img:"https://media.zigcdn.com/media/model/2020/Mar/royal-enfield-bullet-350-right-side-view_600x400.jpg",
            comp_name:"Royal Enfield", 
            range:"270 Km",
            excess:"RS 2/km",
            daily:569,
            Weekly:2799,
            monthly:13899,
            count:6,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"Bullet 350",
        },
        {
            img:"https://media.zigcdn.com/media/model/2021/Sep/2021-classic-350_600x400.jpg",
            comp_name:"Royal Enfield", 
            range:"270 Km",
            excess:"RS 2/km",
            daily:669,
            Weekly:3799,
            monthly:16899,
            count:4,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"Classic 350",
        },
        {
            img:"https://media.zigcdn.com/media/model/2021/Mar/right-side-view-1796007878_930x620.jpg",
            comp_name:"Royal Enfield", 
            range:"270 Km",
            excess:"RS 2/km",
            daily:969,
            Weekly:5999,
            monthly:18899,
            count:3,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"Continental GT 650",
        },
        {
            img:"https://media.zigcdn.com/media/model/2020/Mar/ktm-390-duke-bs6-right-side-view_600x400.jpg",
            comp_name:"KTM",
            range:"270 Km",
            excess:"RS 2/km",
            daily:169,
            Weekly:799,
            monthly:3899,
            count:5,
            minimum_billing:"RS 2/4km",
            type:"Bike",
            name:"390 Duke",
        },
        {
            img:"https://media.zigcdn.com/media/model/2020/Jan/250-duke_600x400.jpg",
            comp_name:"KTM",
            range:"270 Km",
            excess:"RS 2/km",
            daily:569,
            Weekly:3799,
            monthly:11899,
            count:5,
            minimum_billing:"RS 2/4km",
            type:"Bike",
            name:"250 Duke",
        },
        {
            img:"https://images.carandbike.com/bike-images/colors/honda/cb-unicorn-160/honda-cb-unicorn-160-imperial-red-metallic.webp?v=14",
            comp_name:"Honda",
            range:"270 Km",
            excess:"RS 2/km",
            daily:169,
            Weekly:799,
            monthly:3899,
            count:5,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"CB Unicorn 160",
        },
        {
            img:"https://images.carandbike.com/bike-images/colors/bajaj/pulsar-150/bajaj-pulsar-150-neon-red.webp?v=57",
            comp_name:"Bajaj",
            range:"270 Km",
            excess:"RS 2/km",
            daily:169,
            Weekly:799,
            monthly:3899,
            count:5,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"Pulsar 150",
        },
        {
            img:"https://images.carandbike.com/bike-images/colors/bajaj/platina-100/bajaj-platina-100-black.webp?v=27",
            comp_name:"Bajaj",
            range:"270 Km",
            excess:"RS 2/km",
            daily:169,
            Weekly:799,
            monthly:3899,
            count:5,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"Platina 100",
        },
        {
            img:"https://images.carandbike.com/bike-images/colors/hero/super-splendor/hero-super-splendor-heavy-grey.webp?v=25",
            comp_name:"Hero",
            range:"270 Km",
            excess:"RS 2/km",
            daily:169,
            Weekly:799,
            monthly:3899,
            count:5,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"Super Splendor",
        },
        {
            img:"https://images.carandbike.com/bike-images/colors/hero/xtreme-160r/hero-xtreme-160r-pearl-silver-white.webp?v=10",
            comp_name:"Hero",
            range:"270 Km",
            excess:"RS 2/km",
            daily:369,
            Weekly:1099,
            monthly:6899,
            count:5,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"Xtreme 160R",
        },
        {
            img:"https://images.carandbike.com/bike-images/colors/tvs/xl-100/tvs-xl-100-luser-gold.webp?v=13",
            comp_name:"TVS",
            range:"270 Km",
            excess:"RS 2/km",
            daily:169,
            Weekly:799,
            monthly:3899,
            count:5,
            minimum_billing:"RS 100/4km",
            type:"Bike",
            name:"XL100",
        },
        {
            img:"https://images.carandbike.com/bike-images/colors/tvs/raider/tvs-raider-blue.webp?v=10",
            comp_name:"TVS",
            range:"270 Km",
            excess:"RS 2/km",
            daily:269,
            Weekly:1099,
            monthly:4599,
            count:5,
            minimum_billing:"RS 150/4km",
            type:"Bike",
            name:"Raider",
        
        },
        {
            img:"https://images.carandbike.com/bike-images/colors/tvs/scooty-pep-plus/tvs-scooty-pep-plus-revving-red.webp?v=16",
            comp_name:"TVS",
            range:"270 Km",
            excess:"RS 2/km",
            daily:169,
            Weekly:799,
            monthly:3899,
            count:5,
            minimum_billing:"RS 150/4km",
            type:"Moped",
            name:"Scooty Pep Plus",
        
        },
        {
            img:"https://images.carandbike.com/bike-images/colors/hero/maestro-edge/hero-maestro-edge-techno-blue.webp?v=35",
            comp_name:"Hero",
            range:"270 Km",
            excess:"RS 2/km",
            daily:179,
            Weekly:899,
            monthly:3999,
            count:5,
            minimum_billing:"RS 150/4km",
            type:"Moped",
            name:"Maestro Edge",
        },
        {
            img:"https://images.carandbike.com/bike-images/colors/tvs/scooty-zest-110/tvs-scooty-zest-110-matte-purple.webp?v=24",
            comp_name:"TVS",
            range:"270 Km",
            excess:"RS 2/km",
            daily:169,
            Weekly:799,
            monthly:3899,
            count:5,
            minimum_billing:"RS 100/4km",
            type:"Moped",
            name:"Maestro EdgScooty Zest 110",
        },
        ]
        
        localStorage.setItem("product_Data",JSON.stringify(Data));
        console.log(Data.length);
        
}

export default DetailData;